### ISSUE TITLE
Options are read from settings

### ISSUE THREAD

**Issue by stevanmilic** [wimglenn/djangorestframework-queryfields#16]
It would be a nice feature, if we could define `include_arg_name`, `exclude_arg_name` and `delimiter` in _settings.py_.

I'm gonna write PR if I find the time.

**Comment by wimglenn** [comment]
Good suggestion, and should be easy to implement.  PRs welcome!

**Comment by seaworn** [comment]
Added in PR #33

**Comment by wimglenn** [comment]
This is released in [v1.1.0](https://pypi.org/project/djangorestframework-queryfields/1.1.0/).

I've added the test coverage and tweaked the option names to make it a bit more obvious, new doc at https://djangorestframework-queryfields.readthedocs.io/en/latest/faq.html
