### ISSUE TITLE
Feature already implemented in DRF  ^3.4.0? 

### ISSUE THREAD

**Issue by janja-janja** [wimglenn/djangorestframework-queryfields#2]
What's different in this lib?

**Comment by wimglenn** [comment]
You're mistaken, the feature is not implemented in DRF 3.4.0 nor any version of DRF [yet].  You may be confusing the functionality with the ability to specify the fields to serialize on the _server_ side, however this library allows them to be customized by the _client_.

**Comment by dkaranja** [comment]
What do you mean? I am able to request specific fields via a client.
